name: Exploring Variables and Secrets
on: [push]


env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx


jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ vars.DOCKER_PASSWORD }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    steps:
      - name: Docker Build
        run: |
          echo docker build \
            -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DO_USERNAME }}/${{ env.IMAGE_NAME }}:latest


      - name: Docker Login
        run: |
          echo docker login \
            --username=${{ vars.DOCKER_USERNAME }} \
            --password=${{ secrets.DOCKER_PASSWORD }}


      - name: Docker Publish
        run: |
          echo docker push \
            ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest


  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: |
          echo docker run -d -p 8080:80 \
            ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest