name: Exploring Variables and Secrets
on: [push]

env:
  CONTAINER_REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ vars.DOCKER_PASSWORD }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Docker Publish
        run: |
          docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    steps:
      - name: Docker Run
        run: |
          docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
